# Generated by Django 5.0.1 on 2024-03-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], max_length=2, verbose_name='Staat')),
                ('city', models.CharField(max_length=100, verbose_name='Ort')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Postleitzahl')),
                ('street', models.CharField(max_length=100, verbose_name='Straße')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='CameraPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Kameraperspektive',
                'verbose_name_plural': 'Kameraperspektiven',
            },
        ),
        migrations.CreateModel(
            name='ConferencingSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Konferenz Software',
                'verbose_name_plural': 'Konferenz Software',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provides_online_service', models.BooleanField(verbose_name='Online Service gestattet')),
                ('online_service_quality', models.IntegerField(blank=True, choices=[(1, 'Quality 1'), (2, 'Quality 2'), (3, 'Quality 3'), (4, 'Quality 4'), (5, 'Quality 5')], null=True, verbose_name='Online Service Qualität')),
                ('other_rejection_reason', models.TextField(blank=True, max_length=40, null=True, verbose_name='Anderer Ablehnungsgrund')),
                ('creator_ip', models.GenericIPAddressField(verbose_name='IP Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('disabled', models.BooleanField(default=False, verbose_name='Ausgeblendet')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Ablehnungsgrund',
                'verbose_name_plural': 'Ablehnungsgründe',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.TextField(choices=[('OG', 'Oberlandesgericht'), ('LG', 'Landgericht'), ('AG', 'Amtsgericht')], max_length=2, verbose_name='Art')),
                ('online_service_quality', models.FloatField(default=0.0, verbose_name='Online Service Qualität (Cache)')),
                ('provides_online_service_yes_count', models.IntegerField(default=0, verbose_name='Online Service gestattet (Cache)')),
                ('provides_online_service_no_count', models.IntegerField(default=0, verbose_name='Online Service nicht gestattet (Cache)')),
                ('provides_online_service_attr', models.BooleanField(default=False, verbose_name='Online Service gestattet (Bool Cache)')),
                ('online_service_possible_yes_count', models.IntegerField(default=0, verbose_name='Online Service möglich (Cache)')),
                ('online_service_possible_no_count', models.IntegerField(default=0, verbose_name='Online Service nicht möglich (Cache)')),
                ('online_service_possible_attr', models.BooleanField(default=False, verbose_name='Online Service möglich (Bool Cache)')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='court_database.address', verbose_name='Adresse')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='court_database.court', verbose_name='Übergeordnet')),
            ],
            options={
                'verbose_name': 'Gericht',
                'verbose_name_plural': 'Gerichte',
            },
        ),
        migrations.CreateModel(
            name='DetailedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_service_possible', models.BooleanField(verbose_name='Online Service möglich')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('disabled', models.BooleanField(default=False, verbose_name='Ausgeblendet')),
                ('camera_perspectives', models.ManyToManyField(blank=True, to='court_database.cameraperspective', verbose_name='Kameraperspektiven')),
                ('conferencing_software', models.ManyToManyField(blank=True, to='court_database.conferencingsoftware', verbose_name='Konferenzsoftware')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='court_database.court', verbose_name='Gericht')),
            ],
            options={
                'verbose_name': 'Detailliertes Feedback',
                'verbose_name_plural': 'Detaillierte Feedbacks',
            },
        ),
    ]
