# Generated by Django 5.0.1 on 2024-03-27 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court_database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='court_database.court', verbose_name='Gericht'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='court_database.rejectionreason', verbose_name='Ablehnungsgrund'),
        ),
    ]
