# Generated by Django 5.0.1 on 2024-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.TextField(choices=[('BG', 'Bundesgericht'), ('OG', 'Oberlandesgericht'), ('LG', 'Landgericht'), ('AG', 'Amtsgericht')], max_length=2, verbose_name='Art'),
        ),
    ]
