# Generated by Django 5.0.1 on 2024-04-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0003_alter_address_city_alter_address_postal_code_and_more'),
    ]

    @staticmethod
    def create_default_court_types(apps, schema_editor):
        CourtType = apps.get_model('court_database', 'CourtType')
        CourtType.objects.bulk_create([
            CourtType(name='Bundesgericht'),
            CourtType(name='Oberlandesgericht'),
            CourtType(name='Landgericht'),
            CourtType(name='Amtsgericht')
        ])

    @staticmethod
    def derive_new_court_types_from_old_court_types(apps, schema_editor):
        Court = apps.get_model('court_database', 'Court')
        CourtType = apps.get_model('court_database', 'CourtType')
        for court in Court.objects.all():
            if court.type == 'BG':
                court.type_migration_tmp = CourtType.objects.get(name='Bundesgericht')
            elif court.type == 'OG':
                court.type_migration_tmp = CourtType.objects.get(name='Oberlandesgericht')
            elif court.type == 'LG':
                court.type_migration_tmp = CourtType.objects.get(name='Landgericht')
            elif court.type == 'AG':
                court.type_migration_tmp = CourtType.objects.get(name='Amtsgericht')
            court.save()

    operations = [
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Gerichtsart',
                'verbose_name_plural': 'Gerichtsarten',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='type_migration_tmp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='court_database.courttype', verbose_name='Art'),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_court_types),
        migrations.RunPython(derive_new_court_types_from_old_court_types)
    ]
