# Generated by Django 5.0.1 on 2024-04-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0004_courttype_court_type_migration_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='type',
        ),
    ]
