# Generated by Django 5.0.1 on 2024-04-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0005_remove_court_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='type_migration_tmp',
            new_name='type',
        ),
    ]
