# Generated by Django 5.0.1 on 2024-04-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0006_rename_type_migration_tmp_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='court_database.courttype', verbose_name='Art'),
        ),
    ]
