# Generated by Django 5.0.1 on 2025-05-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0007_alter_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
