# Generated by Django 5.0.1 on 2025-07-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0008_alter_court_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfeedback',
            name='from_api',
            field=models.BooleanField(default=False, verbose_name='Von API erstellt'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='api_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer'),
        ),
    ]
