# Generated by Django 5.0.1 on 2025-07-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0009_detailedfeedback_from_api_feedback_api_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='creator_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresse'),
        ),
    ]
