# Generated by Django 5.0.1 on 2025-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0011_address_api_user_cameraperspective_api_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraperspective',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
