# Generated by Django 5.0.1 on 2025-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0012_alter_cameraperspective_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencingsoftware',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
