"""
Django settings for DB128A project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_bootstrap5',
    'mathfilters',
    'helper',
    'cookiebanner',
    'dbbackup',
    'django_object_actions',
    'django_prose_editor',
    'court_database.apps.CourtDatabaseConfig',
    'user_signup.apps.UserSignupConfig',
    'video_conference.apps.VideoConferenceConfig',
    'ai_usage.apps.AiUsageConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DB128A_CONTEXT = os.environ.get("DB128A_CONTEXT")
if DB128A_CONTEXT is None:
    raise Exception('env var DB128A_CONTEXT is not set')
ROOT_URLCONF = f'{DB128A_CONTEXT}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'js_asset.context_processors.importmap',
                'DB128A.context_processors.context_info'
            ],
        },
    },
]

WSGI_APPLICATION = f'DB128A.wsgi_{DB128A_CONTEXT}.application'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user_signup.User'
AUTHENTICATION_BACKENDS = ['user_signup.authentication.EmailBackend']


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# EMail Settings
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS")
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
SERVER_EMAIL = os.environ.get("EMAIL_HOST_USER")

ADMINS = [(os.environ.get("VVDE_ADMIN_NAME"), os.environ.get("VVDE_ADMIN_EMAIL"))]


# cookiebanner

try:
    from DB128A.settings.cookiebanner import COOKIEBANNER
except ImportError as exc:
    raise ImportError(
        "Couldn't import cookiebanner settings. Provide a file called "
        "cookiebanner.py in the settings folder and set the variable "
        "COOKIEBANNER (see https://github.com/sinnwerkstatt/django-cookiebanner)."
    ) from exc


# user_signup

USER_SIGNUP_CAPTCHA_PUBLIC_KEY = os.environ.get("VVDE_USER_SIGNUP_CAPTCHA_PUBLIC_KEY")
USER_SIGNUP_CAPTCHA_SECRET_KEY = os.environ.get("VVDE_USER_SIGNUP_CAPTCHA_SECRET_KEY")


# db_backup

DBBACKUP_GPG_RECIPIENT = os.environ.get("VVDE_GPG_RECIPIENT")
DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DBBACKUP_STORAGE_OPTIONS = {
    'access_key': os.environ.get("VVDE_S3_ACCESS_KEY"),
    'secret_key': os.environ.get("VVDE_S3_SECRET_KEY"),
    'bucket_name': os.environ.get("VVDE_S3_BUCKET_NAME"),
    'default_acl': 'private',
}


# rest_api

COURT_LIST_LIMIT = int(os.environ.get("VVDE_COURT_LIST_LIMIT", 20))
