# Generated by Django 5.0.1 on 2025-09-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court_database', '0014_remove_feedback_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='court_database.court', verbose_name='Gericht')),
            ],
        ),
    ]
