# Generated by Django 5.2.4 on 2025-10-27 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_usage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aifeedback',
            options={'verbose_name': 'KI Feedback', 'verbose_name_plural': 'KI Feedbacks'},
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
