# Generated by Django 5.2.4 on 2025-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_usage', '0002_alter_aifeedback_options_aifeedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'KI-Nutzergruppe',
                'verbose_name_plural': 'KI-Nutzergruppe',
            },
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='usage_groups',
            field=models.ManyToManyField(blank=True, to='ai_usage.aiusagegroup', verbose_name='Nutzergruppen'),
        ),
    ]
