# Generated by Django 5.0.1 on 2025-05-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'verbose_name': 'Passwort-Zurücksetzen-Anfrage', 'verbose_name_plural': 'Passwort-Zurücksetzen-Anfragen'},
        ),
    ]
