# Generated by Django 5.0.1 on 2025-07-22 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court_database', '0013_alter_conferencingsoftware_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Ablehnungsgrund',
                'verbose_name_plural': 'Ablehnungsgründe',
            },
        ),
        migrations.CreateModel(
            name='CameraPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('api_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras_tpm', to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer')),
            ],
            options={
                'verbose_name': 'Kameraperspektive',
                'verbose_name_plural': 'Kameraperspektiven',
            },
        ),
        migrations.CreateModel(
            name='ConferencingSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('api_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conferencing_software_tpm', to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer')),
            ],
            options={
                'verbose_name': 'Konferenz Software',
                'verbose_name_plural': 'Konferenz Software',
            },
        ),
        migrations.CreateModel(
            name='DetailedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_service_possible', models.BooleanField(verbose_name='Online Service möglich')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('disabled', models.BooleanField(default=False, verbose_name='Ausgeblendet')),
                ('from_api', models.BooleanField(default=False, verbose_name='Von API erstellt')),
                ('camera_perspectives', models.ManyToManyField(blank=True, to='video_conference.cameraperspective', verbose_name='Kameraperspektiven')),
                ('conferencing_software', models.ManyToManyField(blank=True, to='video_conference.conferencingsoftware', verbose_name='Konferenzsoftware')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='det_feedbacks_tpm', to='court_database.court', verbose_name='Gericht')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailed_feedbacks_tpm', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Detailliertes Feedback',
                'verbose_name_plural': 'Detaillierte Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provides_online_service', models.BooleanField(verbose_name='Online Service gestattet')),
                ('online_service_quality', models.IntegerField(blank=True, choices=[(1, 'Quality 1'), (2, 'Quality 2'), (3, 'Quality 3'), (4, 'Quality 4'), (5, 'Quality 5')], null=True, verbose_name='Online Service Qualität')),
                ('other_rejection_reason', models.TextField(blank=True, max_length=40, null=True, verbose_name='Anderer Ablehnungsgrund')),
                ('creator_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt')),
                ('disabled', models.BooleanField(default=False, verbose_name='Ausgeblendet')),
                ('api_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_tpm', to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_tpm', to='court_database.court', verbose_name='Gericht')),
                ('rejection_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='video_conference.rejectionreason', verbose_name='Ablehnungsgrund')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
