# Generated by Django 5.0.1 on 2025-07-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_database', '0014_remove_feedback_models'),
        ('video_conference', '0002_migrate_feedback_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraperspective',
            name='api_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer'),
        ),
        migrations.AlterField(
            model_name='conferencingsoftware',
            name='api_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer'),
        ),
        migrations.AlterField(
            model_name='detailedfeedback',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='court_database.court', verbose_name='Gericht'),
        ),
        migrations.AlterField(
            model_name='detailedfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='api_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='API Benutzer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='court_database.court', verbose_name='Gericht'),
        ),
    ]
